server:
  port: 10011
spring:
  application:
    name: config-server
  profiles:
#    active: native
    active: dev
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: E:/workspace/damontest/config/dev
#          default-label: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/damoncl/config.git
          username: damoncl92@163.com
          password: cl964251259
          search-paths: ${spring.profiles.active}
          basedir: E:/workspace/temp-git
          default-label: dev
  security:
    user:
      name: damon
      password: 111111
eureka:
  instance:
    #\u5FC3\u8DF3\u65F6\u95F4\uFF0C\u670D\u52A1\u7EED\u7EA6\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u4E3A30s
    lease-renewal-interval-in-seconds: 5
    #\u670D\u52A1\u7EED\u7EA6\u5230\u671F\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u4E3A90s
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      user.name: damon
      user.password: 111111
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: http://peer1:10001/eureka,http://peer2:10002/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: haier
    password: Haier
